import React, { useState } from "react";
import { Alert, Badge, Button, Checkbox, Dialog, EmptyState, Field, IconButton, Input, Loading, Menu, MenuItem, Page, PageHeader, Panel, PanelContent, PanelFooter, PanelHeader, Popover, Select, Switch, Textarea, Tooltip, UIProvider } from "@semicoder/malatang-sdk/ui";
export default function ComponentGallery() {
  const [checked, setChecked] = useState(false), [visible, setVisible] = useState(true);
  return <Page><PageHeader title="组件样例" description="开发专用。通过侧栏切换浅色、深色与系统主题，检查键盘、焦点及状态。" /><div className="gallery-stack">
    <Panel><PanelHeader>控件与状态</PanelHeader><PanelContent><div className="gallery-row">{(["primary", "secondary", "ghost", "danger"] as const).map(variant => <React.Fragment key={variant}><Button variant={variant} size="sm">{variant} sm</Button><Button variant={variant}>md</Button></React.Fragment>)}<Button disabled>禁用</Button><Button loading>保存中</Button><Tooltip content="有标签的图标按钮"><IconButton label="添加示例">＋</IconButton></Tooltip><Loading /></div></PanelContent><PanelFooter><Badge>默认</Badge><Badge tone="success">完成</Badge><Badge tone="warning">等待</Badge><Badge tone="error">错误</Badge></PanelFooter></Panel>
    <Panel><PanelHeader>标签、错误与键盘</PanelHeader><PanelContent><Field label="显示名称" hint="点击标签应聚焦输入框"><Input placeholder="请输入名称" /></Field><Field label="错误输入" error="请填写有效内容"><Input defaultValue="?" /></Field><Field label="尺寸 sm"><Input size="sm" /></Field><Field label="禁用输入"><Input disabled /></Field><Field label="选择"><Select><option>选项 A</option><option>选项 B</option></Select></Field><Field label="多行内容"><Textarea /></Field><Field label="同意示例"><Checkbox /></Field><Field label="自动保存"><Switch checked={checked} onCheckedChange={setChecked} /></Field></PanelContent></Panel>
    <Panel><PanelHeader>页面弹层</PanelHeader><PanelContent><div className="gallery-row"><Menu trigger={<Button>菜单</Button>}><MenuItem onSelect={() => setChecked(value => !value)}>切换自动保存</MenuItem><MenuItem disabled>不可用选项</MenuItem></Menu><Popover trigger={<Button variant="secondary">浮层</Button>}><Field label="浮层输入"><Input /></Field></Popover><Dialog title="嵌套弹层" description="Tab 保持在对话框内，Escape 先关闭最内层。" trigger={<Button>打开对话框</Button>}><Field label="对话框输入"><Input /></Field><Popover trigger={<Button variant="secondary">嵌套浮层</Button>}><Field label="嵌套输入"><Input /></Field></Popover></Dialog><Button variant="secondary" onClick={() => setVisible(value => !value)}>切换保留页面</Button></div><UIProvider visible={visible}><div hidden={!visible}><Popover trigger={<Button variant="ghost">保留页面浮层</Button>}><Button onClick={() => setVisible(false)}>隐藏所属页面</Button></Popover></div></UIProvider></PanelContent></Panel>
    <Alert tone="neutral">说明提示</Alert><Alert tone="success">保存完成</Alert><Alert tone="warning">等待配置</Alert><Alert>请求失败，可重试</Alert><EmptyState title="尚无内容" description="公共空状态组件" />
  </div></Page>;
}
