import React, { useEffect, useState } from "react";
import { Badge, Button, Field, PageHeader, Panel } from "@malatang/sdk/ui";
import type { ModelInfo } from "@malatang/sdk/types";
import { app } from "./bridge";
const blank = { name: "", provider: "OpenAI Compatible", model: "", baseURL: "https://api.openai.com/v1", apiKey: "" };
export default function ModelSettings() {
  const [models, setModels] = useState<ModelInfo[]>([]);
  const [form, setForm] = useState(blank);
  const [editing, setEditing] = useState<string>();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const refresh = () => app.call("models.list", {}).then(setModels).catch(e => setError(String(e)));
  useEffect(() => { const off = app.on("models.changed", () => void refresh()); const reconnect = app.onReconnect(() => void refresh()); void refresh(); return () => { off(); reconnect(); }; }, []);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); setSuccess(""); try { await app.call("models.save", { ...form, ...(editing ? { id: editing } : {}) }); setSuccess("模型已保存，可在插件中选择。连接会在首次调用时验证。"); setForm(blank); setEditing(undefined); } catch (e) { setError(String(e)); } finally { setBusy(false); } };
  return <div className="m-page"><PageHeader eyebrow="ONE CONFIGURATION, EVERY APPLICATION" title="你的模型，随处可用。" description="在这里配置一次，让每个应用都能使用。" actions={<Badge>{models.length} 个模型</Badge>} /><div className="settings-grid"><section><h2 className="small-heading">可用模型</h2><div className="model-list">{models.map(model => <Panel key={model.id} className="model-card"><div className="model-icon">{model.kind === "demo" ? "✦" : "◈"}</div><div className="model-details"><strong>{model.name}</strong><p>{model.provider} · {model.model}</p><Badge tone={model.kind === "demo" ? "amber" : model.configured ? "green" : "neutral"}>{model.kind === "demo" ? "交互演示" : model.configured ? "已配置 · 连接待调用验证" : "未设置密钥"}</Badge></div>{model.kind !== "demo" && <div className="model-controls"><Button variant="ghost" onClick={() => { setEditing(model.id); setForm({ name: model.name, provider: model.provider, model: model.model, baseURL: model.baseURL, apiKey: "" }); setSuccess(""); }}>编辑</Button><Button variant="ghost" disabled={busy} onClick={() => { setBusy(true); void app.call("models.remove", { id: model.id }).catch(e => setError(String(e))).finally(() => setBusy(false)); }}>删除</Button></div>}</Panel>)}</div><div className="m-callout">演示模型不连接网络，仅对翻译示例返回预置文本。添加兼容 Chat Completions 流式接口的服务，开始使用真实模型。</div></section><Panel className="settings-form"><h2>{editing ? "编辑模型" : "添加模型"}</h2><form onSubmit={event => void save(event)}><Field label="显示名称"><input required aria-label="显示名称" placeholder="例如：我的日常模型" maxLength={100} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></Field><Field label="服务商"><input required aria-label="服务商" value={form.provider} onChange={e => setForm({ ...form, provider: e.target.value })} /></Field><Field label="API Base URL" hint="填写 API 根路径，例如 https://example.com/v1"><input required type="url" aria-label="API Base URL" value={form.baseURL} onChange={e => setForm({ ...form, baseURL: e.target.value })} /></Field><Field label="模型 ID"><input required aria-label="模型 ID" placeholder="服务商提供的 model ID" maxLength={200} value={form.model} onChange={e => setForm({ ...form, model: e.target.value })} /></Field><Field label="API Key" hint={editing ? "留空保留原密钥。密钥不会返回到前端。" : "密钥仅保存在本机宿主配置中。"}><input type="password" aria-label="API Key" autoComplete="off" value={form.apiKey} onChange={e => setForm({ ...form, apiKey: e.target.value })} placeholder={editing ? "留空保留现有密钥" : "sk-…"} /></Field><div className="form-actions">{editing && <Button variant="ghost" type="button" onClick={() => { setEditing(undefined); setForm(blank); }}>取消编辑</Button>}<Button type="submit" disabled={busy}>{busy ? "保存中…" : "保存模型 ↗"}</Button></div></form></Panel></div>{error && <p role="alert" className="m-error">{error}</p>}{success && <p role="status" className="success-message">✓ {success}</p>}</div>;
}
